ALTER SESSION SET QUERY_TAG = 'OSDI_REWARDS_CALC_001';

CREATE OR REPLACE TABLE LOB_DB_COLLAB.LOB_REWARDS.STG_CATEGORIZED_TRANSACTIONS AS
SELECT
    t.TRANSACTION_ID,
    t.ACCOUNT_ID,
    t.MERCHANT_NAME,
    t.MCC_CODE,
    t.TRANSACTION_AMOUNT,
    t.TRANSACTION_DATE,
    CASE
        WHEN t.MCC_CODE IN ('5811','5812','5813','5814') THEN 'Dining'
        WHEN t.MCC_CODE IN ('5499') THEN 'Dining - Uber Eats'
        WHEN t.MCC_CODE IN ('5411','5422','5441','5451') THEN 'Grocery'
        WHEN t.MCC_CODE IN ('4121','4131','4011','4112') THEN 'Travel'
        WHEN t.MCC_CODE IN ('5732','5734','5945','5947') THEN 'Electronics'
        ELSE 'General'
    END AS SPENDING_CATEGORY
FROM LOB_DB_COLLAB.LOB_REWARDS.CARD_TRANSACTIONS t
WHERE t.TRANSACTION_STATUS = 'APPROVED';

CREATE OR REPLACE TABLE LOB_DB_COLLAB.LOB_REWARDS.STG_TRANSACTION_REWARDS AS
SELECT
    ct.TRANSACTION_ID,
    ct.ACCOUNT_ID,
    ct.MERCHANT_NAME,
    ct.SPENDING_CATEGORY,
    ct.TRANSACTION_AMOUNT,
    ct.TRANSACTION_DATE,
    r.POINTS_MULTIPLIER,
    ROUND(ct.TRANSACTION_AMOUNT * r.POINTS_MULTIPLIER, 0) AS POINTS_EARNED
FROM LOB_DB_COLLAB.LOB_REWARDS.STG_CATEGORIZED_TRANSACTIONS ct
JOIN LOB_DB_COLLAB.LOB_REWARDS.REWARDS_CATEGORIES r
    ON ct.SPENDING_CATEGORY = r.CATEGORY_NAME;
